<?php

class m_grafik extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    //------------- high chart
    public function grafikDivisi() {
        $query = $this->db->query("SELECT U.NAMA_UNIT, (SELECT COUNT(P.ID_PEGAWAI) FROM PEGAWAI P, LOG_JABATAN LJ WHERE P.ID_PEGAWAI=LJ.ID_PEGAWAI AND LJ.STATUS_JABATAN=1 AND U.ID_UNIT=LJ.ID_UNIT AND LJ.STATUS_JABATAN=1 AND P.STATUS_AKTIF=1) AS JUMLAH, 
        (SELECT COUNT(P.ID_PEGAWAI) FROM PEGAWAI P, LOG_JABATAN LJ WHERE P.ID_PEGAWAI=LJ.ID_PEGAWAI AND LJ.STATUS_JABATAN=1 AND U.ID_UNIT=LJ.ID_UNIT AND LJ.STATUS_JABATAN=1 AND P.JENIS_KELAMIN='LAKI-LAKI' AND P.STATUS_AKTIF=1) AS LAKI,
        (SELECT COUNT(P.ID_PEGAWAI) FROM PEGAWAI P, LOG_JABATAN LJ WHERE P.ID_PEGAWAI=LJ.ID_PEGAWAI AND LJ.STATUS_JABATAN=1 AND U.ID_UNIT=LJ.ID_UNIT AND LJ.STATUS_JABATAN=1 AND P.JENIS_KELAMIN='PEREMPUAN' AND P.STATUS_AKTIF=1) AS PEREMPUAN
        FROM UNIT_KERJA U;");
        return $query->result();
    }

    public function grafikPegawaiDivisi($bagian) {
        $query = $this->db->query("SELECT JJ.JABATAN, 
        (SELECT COUNT(P.ID_PEGAWAI) AS JUMLAH FROM PEGAWAI P, LOG_JABATAN LJ, JABATAN J WHERE LJ.ID_PEGAWAI=P.ID_PEGAWAI AND LJ.ID_JENIS_JABATAN=J.ID_JENIS_JABATAN AND LJ.STATUS_JABATAN='1' AND JJ.ID_JENIS_JABATAN=J.ID_JENIS_JABATAN AND LJ.STATUS_JABATAN=1 AND P.STATUS_AKTIF=1) AS JUMLAH, 
        (SELECT COUNT(P.ID_PEGAWAI) AS JUMLAH FROM PEGAWAI P, LOG_JABATAN LJ, JABATAN J WHERE LJ.ID_PEGAWAI=P.ID_PEGAWAI AND LJ.ID_JENIS_JABATAN=J.ID_JENIS_JABATAN AND LJ.STATUS_JABATAN='1' AND JJ.ID_JENIS_JABATAN=J.ID_JENIS_JABATAN AND LJ.STATUS_JABATAN=1 AND P.JENIS_KELAMIN='LAKI-LAKI' AND P.STATUS_AKTIF=1) AS LAKI,
        (SELECT COUNT(P.ID_PEGAWAI) AS JUMLAH FROM PEGAWAI P, LOG_JABATAN LJ, JABATAN J WHERE LJ.ID_PEGAWAI=P.ID_PEGAWAI AND LJ.ID_JENIS_JABATAN=J.ID_JENIS_JABATAN AND LJ.STATUS_JABATAN='1' AND JJ.ID_JENIS_JABATAN=J.ID_JENIS_JABATAN AND LJ.STATUS_JABATAN=1 AND P.JENIS_KELAMIN='PEREMPUAN' AND P.STATUS_AKTIF=1) AS PEREMPUAN  
        FROM JABATAN JJ 
        WHERE JJ.BAGIAN=$bagian");
        return $query->result();
    }

    public function grafikGolongan() {
        $query = $this->db->query("SELECT JG.GOLONGAN, 
        (SELECT COUNT(P.ID_PEGAWAI ) FROM PEGAWAI P, LOG_KEPANGKATAN LK WHERE P.ID_PEGAWAI=LK.ID_PEGAWAI AND LK.ID_JENIS_GOLONGAN=JG.ID_JENIS_GOLONGAN AND P.STATUS_AKTIF=1) AS JUMLAH,
        (SELECT COUNT(P.ID_PEGAWAI ) FROM PEGAWAI P, LOG_KEPANGKATAN LK WHERE P.ID_PEGAWAI=LK.ID_PEGAWAI AND LK.ID_JENIS_GOLONGAN=JG.ID_JENIS_GOLONGAN AND P.JENIS_KELAMIN='LAKI-LAKI' AND P.STATUS_AKTIF=1) AS LAKI,
        (SELECT COUNT(P.ID_PEGAWAI ) FROM PEGAWAI P, LOG_KEPANGKATAN LK WHERE P.ID_PEGAWAI=LK.ID_PEGAWAI AND LK.ID_JENIS_GOLONGAN=JG.ID_JENIS_GOLONGAN AND P.JENIS_KELAMIN='PEREMPUAN' AND P.STATUS_AKTIF=1) AS PEREMPUAN   
        FROM JENIS_GOLONGAN JG");
        return $query->result();
    }

    public function grafikPerGolongan($golongan) {
        $query = $this->db->query("SELECT JG.GOLONGAN, (SELECT COUNT(P.ID_PEGAWAI ) FROM PEGAWAI P, LOG_KEPANGKATAN LK WHERE P.ID_PEGAWAI=LK.ID_PEGAWAI AND LK.ID_JENIS_GOLONGAN=JG.ID_JENIS_GOLONGAN  AND P.ID_PEGAWAI<>-1 AND P.STATUS_AKTIF=1) AS JUMLAH, "
                . "(SELECT COUNT(P.ID_PEGAWAI ) FROM PEGAWAI P, LOG_KEPANGKATAN LK WHERE P.ID_PEGAWAI=LK.ID_PEGAWAI AND LK.ID_JENIS_GOLONGAN=JG.ID_JENIS_GOLONGAN AND P.JENIS_KELAMIN='LAKI-LAKI'  AND P.ID_PEGAWAI<>-1 AND P.STATUS_AKTIF=1) AS LAKI, "
                . "(SELECT COUNT(P.ID_PEGAWAI ) FROM PEGAWAI P, LOG_KEPANGKATAN LK WHERE P.ID_PEGAWAI=LK.ID_PEGAWAI AND LK.ID_JENIS_GOLONGAN=JG.ID_JENIS_GOLONGAN AND P.JENIS_KELAMIN='PEREMPUAN'  AND P.ID_PEGAWAI<>-1 AND P.STATUS_AKTIF=1) AS PEREMPUAN "
                . "FROM JENIS_GOLONGAN JG "
                . "WHERE JG.GOLONGAN = '$golongan' ");
        return $query->result();
    }

    public function grafikStatusPegawai() {
        $query = $this->db->query("SELECT STATUS_PEGAWAI, COUNT(ID_PEGAWAI)AS JUMLAH , 
        (SELECT COUNT(ID_PEGAWAI) AS LAKI FROM PEGAWAI WHERE JENIS_KELAMIN='LAKI-LAKI' AND STATUS_AKTIF=1) AS LAKI, 
        (SELECT COUNT(ID_PEGAWAI) AS LAKI FROM PEGAWAI WHERE JENIS_KELAMIN='PEREMPUAN' AND STATUS_AKTIF=1) AS PEREMPUAN 
        FROM PEGAWAI WHERE  ID_PEGAWAI<>-1 AND STATUS_AKTIF=1 GROUP BY STATUS_PEGAWAI");
        return $query->result();
    }

    public function grafikPerStatusPegawai($status_pegawai) {
        $query = $this->db->query("SELECT STATUS_PEGAWAI, COUNT(ID_PEGAWAI) AS JUMLAH, 
        (SELECT COUNT(ID_PEGAWAI) AS JUMLAH FROM PEGAWAI WHERE JENIS_KELAMIN='LAKI-LAKI' AND STATUS_AKTIF=1) AS LAKI,
        (SELECT COUNT(ID_PEGAWAI) AS JUMLAH FROM PEGAWAI WHERE JENIS_KELAMIN='PEREMPUAN' AND STATUS_AKTIF=1) AS PEREMPUAN
        FROM PEGAWAI WHERE STATUS_PEGAWAI='$status_pegawai' AND STATUS_AKTIF=1");
        return $query->result();
    }

    public function grafikPendidikan() {
        $query = $this->db->query("SELECT LP.TINGKAT_PENDIDIKAN,
        (SELECT COUNT(LPN.ID_PEGAWAI)FROM LOG_PENDIDIKAN LPN, PEGAWAI P WHERE LPN.TINGKAT_PENDIDIKAN=LP.TINGKAT_PENDIDIKAN AND P.ID_PEGAWAI=LPN.ID_PEGAWAI AND P.STATUS_AKTIF=1) AS JUMLAH,
        (SELECT COUNT(LPN.ID_PEGAWAI)FROM LOG_PENDIDIKAN LPN, PEGAWAI P WHERE LPN.TINGKAT_PENDIDIKAN=LP.TINGKAT_PENDIDIKAN AND P.ID_PEGAWAI=LPN.ID_PEGAWAI AND P.JENIS_KELAMIN='LAKI-LAKI' AND P.STATUS_AKTIF=1) AS LAKI,
        (SELECT COUNT(LPN.ID_PEGAWAI)FROM LOG_PENDIDIKAN LPN, PEGAWAI P WHERE LPN.TINGKAT_PENDIDIKAN=LP.TINGKAT_PENDIDIKAN AND P.ID_PEGAWAI=LPN.ID_PEGAWAI AND P.JENIS_KELAMIN='PEREMPUAN' AND P.STATUS_AKTIF=1) AS PEREMPUAN
        FROM LOG_PENDIDIKAN LP
        WHERE LP.KETERANGAN_PENDIDIKAN=1 AND STATUS_PENDIDIKAN_TERAKHIR=1
        GROUP BY LP.TINGKAT_PENDIDIKAN");
        return $query->result();
    }

    public function grafikPerPendidikan($tingkat_pendidikan) {
        $query = $this->db->query("SELECT LP.TINGKAT_PENDIDIKAN,
        (SELECT COUNT(LPN.ID_PEGAWAI)FROM LOG_PENDIDIKAN LPN, PEGAWAI P WHERE LPN.TINGKAT_PENDIDIKAN=LP.TINGKAT_PENDIDIKAN AND P.ID_PEGAWAI=LPN.ID_PEGAWAI AND P.STATUS_AKTIF=1) AS JUMLAH,
        (SELECT COUNT(LPN.ID_PEGAWAI)FROM LOG_PENDIDIKAN LPN, PEGAWAI P WHERE LPN.TINGKAT_PENDIDIKAN=LP.TINGKAT_PENDIDIKAN AND P.ID_PEGAWAI=LPN.ID_PEGAWAI AND P.JENIS_KELAMIN='LAKI-LAKI' AND P.STATUS_AKTIF=1) AS LAKI,
        (SELECT COUNT(LPN.ID_PEGAWAI)FROM LOG_PENDIDIKAN LPN, PEGAWAI P WHERE LPN.TINGKAT_PENDIDIKAN=LP.TINGKAT_PENDIDIKAN AND P.ID_PEGAWAI=LPN.ID_PEGAWAI AND P.JENIS_KELAMIN='PEREMPUAN' AND P.STATUS_AKTIF=1) AS PEREMPUAN
        FROM LOG_PENDIDIKAN LP
        WHERE LP.KETERANGAN_PENDIDIKAN=1 AND STATUS_PENDIDIKAN_TERAKHIR=1 AND LP.TINGKAT_PENDIDIKAN='$tingkat_pendidikan'
        GROUP BY LP.TINGKAT_PENDIDIKAN");
        return $query->result();
    }

    public function grafikJenjangUmur() {
        $query = $this->db->query("SELECT DISTINCT IF(ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0) <=10,'0-10', IF(ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0) >10 AND ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0)<=20,'10-19', IF(ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0) >20 AND 
        ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0)<30,'20-29',
        IF(ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0) >=30 AND 
        ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0)<40,'30-39',
        IF(ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0) >=40 AND 
        ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0)<50,'40-49',
	IF(ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0) >=50 AND 
        ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0)<100,'>50','-')))))) 
        AS UMUR , COUNT(*) AS JUMLAH FROM PEGAWAI WHERE STATUS_AKTIF=1
        GROUP BY UMUR ORDER BY UMUR");
        return $query->result();
    }

    public function grafikPerJenjangUmur($awal, $akhir) {
        $query = $this->db->query("SELECT DISTINCT IF(ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0) <=10,'0-10', IF(ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0) >10 AND ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0)<=20,'10-19',IF(ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0) >20 AND ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0)<=30,'20-29',
        IF(ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0) >30 AND 
        ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0)<=40,'30-39',
        IF(ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0) >40 AND 
        ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0)<=50,'40-49','>50'))))) 
        AS UMUR, count(*) AS JUMLAH, JENIS_KELAMIN
	FROM PEGAWAI P WHERE P.STATUS_AKTIF=1 AND ROUND(DATEDIFF(NOW(),TGL_LAHIR)/365,0) BETWEEN $awal AND $akhir
        group by jenis_kelamin");
        return $query->result();
    }

    public function grafikCuti() {
        $query = $this->db->query("SELECT ID_CUTI, TGL_MULAI_CUTI, TGL_SELESAI_CUTI
        FROM LOG_CUTI
        WHERE ACC_CUTI=1");
       return $query->result();
    }

    public function grafikCutiPerbulan() {
        $query = $this->db->query("SELECT * 
        from PEGAWAI P, LOG_CUTI LC
        WHERE P.ID_PEGAWAI=LC.ID_PEGAWAI and p.status_aktif=1 and LC.ACC_CUTI=0");
       return $query->result();
    }

    public function tabelPegawaiDivisi($bagian) {
        $query = $this->db->query("SELECT P.NIP, P.NAMA_PEGAWAI, P.GELAR_DEPAN, P.GELAR_BELAKANG, P.JENIS_KELAMIN, JG.GOLONGAN, J.JABATAN, U.NAMA_UNIT "
                . "FROM PEGAWAI P, UNIT_KERJA U, LOG_JABATAN LJ, JABATAN J, LOG_KEPANGKATAN LK, JENIS_GOLONGAN JG "
                . "WHERE LJ.ID_UNIT=U.ID_UNIT AND P.ID_PEGAWAI=LJ.ID_PEGAWAI AND LJ.ID_JENIS_JABATAN=J.ID_JENIS_JABATAN AND P.ID_PEGAWAI=LK.ID_PEGAWAI AND LK.ID_JENIS_GOLONGAN=JG.ID_JENIS_GOLONGAN AND LJ.STATUS_JABATAN=1 AND P.STATUS_AKTIF=1 AND J.BAGIAN='$bagian'");
        return $query->result();
    }

    public function tabelPegawai($where) {
        $query = $this->db->query("SELECT P.ID_PEGAWAI, P.NIP, P.NAMA_PEGAWAI, P.GELAR_DEPAN, P.GELAR_BELAKANG, JG.GOLONGAN, P.JENIS_KELAMIN, LP.TINGKAT_PENDIDIKAN, J.JABATAN, U.NAMA_UNIT
        FROM PEGAWAI P, UNIT_KERJA U, JABATAN J, LOG_JABATAN LJ, LOG_PENDIDIKAN LP, JENIS_GOLONGAN JG, LOG_KEPANGKATAN LK
        WHERE P.ID_PEGAWAI=LJ.ID_PEGAWAI AND LJ.ID_JENIS_JABATAN=J.ID_JENIS_JABATAN AND LJ.ID_UNIT=U.ID_UNIT AND LP.ID_PEGAWAI=P.ID_PEGAWAI AND LP.STATUS_PENDIDIKAN_TERAKHIR=1 AND LP.KETERANGAN_PENDIDIKAN=1 AND LK.ID_PEGAWAI=P.ID_PEGAWAI AND LK.ID_JENIS_GOLONGAN=JG.ID_JENIS_GOLONGAN AND LJ.STATUS_JABATAN=1 AND P.STATUS_AKTIF=1 $where
        ORDER BY P.NAMA_PEGAWAI ");
        return $query->result();
    }

}
